spring:
  main:
    allow-circular-references: true
  config:
    activate:
      on-profile: default

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pracsecurity_schema
    username: practiceAccount
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100

  messages:
    basename: errors

logging:
  level:
    root: warn
    com.pracsecurity: debug

